extern crate alloc;

use crate::gerr_box::GErrBox;
use crate::gerr_source::DataSource;
use crate::gerr_source::GErrSource;
use crate::gerr_source::IdSource;
use crate::types::{NoData, NoID, NoPrefix};

use core::{
    error::Error,
    fmt::{Debug, Display},
    marker::PhantomData,
    panic::Location,
};

#[cfg(feature = "backtrace")]
use std::backtrace::Backtrace;

use alloc::borrow::Cow;

/// Trait for auto-generating the error id.
pub trait Id {
    fn id() -> Self;
}

/// Trait for prefix generation.
pub trait Prefix {
    const PREFIX: Option<&'static str> = None;
}

/// Trait for upserting error data.
///
/// Self must implement `Default`.
pub trait SetField<K, V> {
    fn set_field(&mut self, key: K, value: V);
}

/// Alias for core's Result.
pub type Result<T, ID = NoID, P = NoPrefix, D = NoData> = core::result::Result<T, GErr<ID, P, D>>;

/// Default GErr without ID, Prefix and Data.
pub type GErrDefault = GErr<NoID, NoPrefix, NoData>;

/// GErr - Generic and configurable error type.
///
/// It contains type parameters error id(`ID`), prefix(`P`), and generic error data(`D`).
///
/// *ID*, error id:
/// - Can be supplied manually or automatically through [`Id`] trait.
/// - Implementing [`Id`] is optional only when id needs to be auto-generated.
/// - Must implements `Debug` and `Display`.
/// - If `serde` feature enabled, must implements [`::serde::Serialize`].
///
/// *P*, error prefix:
/// - Can be supplied manually or automatically through [`Prefix`] trait.
/// - Implementing [`Prefix`] is optional only when prefix needs to be auto-generated.
///
/// *D*, error data:
/// - Can be supplied manually through methods: [`GErr::set_data`] or [`GErr::with_data`] to change data's type.
/// - Must implemented `Debug`.
/// - If `serde` feature enabled, must implements [`::serde::Serialize`].
///
/// Error location is automatically generated through some methods.
///
/// It contains stack-trace if `backtrace` feature is enabled.
///
/// [`NoID`] is provided as default if you want no id and it implements trait `Id`.
///
/// [`NoPrefix`] is provided as default if you want no prefix and it implements trait `prefix`.
///
/// [`NoData`] is provided as default if you want no data and it will serde to null for json.
///
/// GErr contains error as having these attributes:
/// - `id`: The error id. This is to identify the error. I can be autogenerated or from outside(e.g. request id).
/// - `message`: The error message.
/// - `prefix`: The error prefix. Acts as label/category/group of errors.
/// - `sources`: The sources of current error. Errors can be linked/chained from multiple errors, serial or parallel.
/// - `tags`: The error tags. Things related with the error. For easy querying.
/// - `data`: The error data. This is additional data about the error. It can be error kinds(enum), user data triggering the errors, etc.
/// - `help`: Hint about how to solve the error.
/// - `location`: Where the error happen.
/// - `backtrace`: The error stacktrace, feature-gated behind `backtrace`.
///
/// # Note
/// Set aside size of error ID and Data:
///
/// - `GErr<NoID, NoPrefix, NoData>` is approximately 136 bytes.
/// - Enabling the `backtrace` feature increases this to approximately
///   184 bytes (+48 bytes from `Backtrace`).
///
/// Clippy's `result_large_err` lint is intentionally allowed for this crate.
/// Users requiring a smaller error representation may box `GErr` in their
/// own APIs or using provided [`GErrBox`].
pub struct GErr<ID = NoID, P = NoPrefix, D = NoData> {
    id: Option<ID>,
    message: Cow<'static, str>,

    prefix: Option<Cow<'static, str>>,
    sources: Option<Vec<GErrSource>>,

    tags: Option<Vec<Cow<'static, str>>>,

    data: Option<D>,

    help: Option<Cow<'static, str>>,

    location: &'static Location<'static>,

    #[cfg(feature = "backtrace")]
    backtrace: Backtrace,

    _static_prefix: PhantomData<P>,
}

impl<ID, P, D> GErr<ID, P, D> {
    /// Constructs new GErr without id.
    #[track_caller]
    #[inline]
    pub fn new<M>(message: M) -> Self
    where
        M: Into<Cow<'static, str>>,
    {
        Self {
            id: None,
            message: message.into(),

            prefix: None,
            sources: None,

            tags: None,

            data: None,

            help: None,

            location: Location::caller(),

            #[cfg(feature = "backtrace")]
            backtrace: Backtrace::capture(),

            _static_prefix: PhantomData,
        }
    }
}

impl<ID: Id, P: Prefix, D> GErr<ID, P, D> {
    /// Constructs new GErr with message and auto-generated id.
    #[track_caller]
    #[inline]
    pub fn new_auto<M>(message: M) -> Self
    where
        M: Into<Cow<'static, str>>,
    {
        Self::new_auto_untracked(message, Location::caller())
    }

    #[inline]
    pub(crate) fn new_auto_untracked<M>(message: M, location: &'static Location<'static>) -> Self
    where
        M: Into<Cow<'static, str>>,
    {
        Self::new_with_id_untracked(Some(ID::id()), message.into(), location)
    }

    /// Constructs new GErr from any error implementing trait [`Error`]
    ///
    /// Id is auto-generated and only contains message, location and the error as source.
    #[track_caller]
    #[inline]
    pub fn from_error<E>(err: E) -> Self
    where
        E: Error + Send + Sync + 'static,
    {
        Self::new_auto_untracked(err.to_string(), Location::caller()).add_source(err)
    }
}

impl<ID, P: Prefix, D> GErr<ID, P, D> {
    /// Constructs new GErr with id and message.
    ///
    /// This is to set error id manually.
    #[track_caller]
    #[inline]
    pub fn new_with_id<M>(id: ID, message: M) -> Self
    where
        M: Into<Cow<'static, str>>,
    {
        Self::new_with_id_untracked(Some(id), message, Location::caller())
    }

    #[inline]
    pub(crate) fn new_with_id_untracked<M>(
        id: Option<ID>,
        message: M,
        location: &'static Location<'static>,
    ) -> Self
    where
        M: Into<Cow<'static, str>>,
    {
        Self {
            id,
            message: message.into(),

            prefix: P::PREFIX.map(Cow::Borrowed),
            sources: None,

            tags: None,

            data: None,

            help: None,

            location,

            #[cfg(feature = "backtrace")]
            backtrace: Backtrace::capture(),

            _static_prefix: PhantomData,
        }
    }

    /// Constructs new GErr from any error implementing trait [`Error`]
    ///
    /// Id is manually-set and only contains message, location and the error as source.
    #[track_caller]
    #[inline]
    pub fn from_error_with_id<E>(id: ID, err: E) -> Self
    where
        E: Error + Send + Sync + 'static,
    {
        Self::new_with_id_untracked(Some(id), err.to_string(), Location::caller()).add_source(err)
    }
}

impl<ID, P: Prefix, D> GErr<ID, P, D> {
    /// Update error id where id's type is the same as `ID` type parameter.
    #[must_use]
    #[inline]
    pub fn set_id(mut self, id: ID) -> Self {
        self.id = Some(id);
        self
    }

    /// Update prefix.
    #[must_use]
    #[inline]
    pub fn set_prefix<T>(mut self, prefix: T) -> Self
    where
        T: Into<Cow<'static, str>>,
    {
        self.prefix = Some(prefix.into());
        self
    }

    /// Update prefix by prepending onto existing prefix.
    ///
    /// If current prefix is empty, this becomes the prefix.
    #[must_use]
    #[inline]
    pub fn prepend_prefix<T>(mut self, pre_prefix: T) -> Self
    where
        T: Into<Cow<'static, str>> + AsRef<str>,
    {
        match self.prefix.as_mut() {
            Some(p) => {
                p.to_mut().insert_str(0, pre_prefix.as_ref());
            }
            None => self.prefix = Some(pre_prefix.into()),
        }

        self
    }

    /// Update prefix by appending into existing prefix.
    ///
    /// If current prefix is empty, this becomes the prefix.
    #[must_use]
    #[inline]
    pub fn append_prefix<T>(mut self, post_prefix: T) -> Self
    where
        T: Into<Cow<'static, str>> + AsRef<str>,
    {
        match self.prefix.as_mut() {
            Some(p) => {
                p.to_mut().push_str(post_prefix.as_ref());
            }
            None => self.prefix = Some(post_prefix.into()),
        }

        self
    }

    /// Add general error into list of sources.
    ///
    /// If you're passing GErr, convert it into [`GErrSource`] first using [`GErr::into_gerr_source`] or `Into`
    /// to parse the error with detailed attributes of GErr, or use [`GErr::add_source_gerr`] without conversion to GErrSource.
    #[must_use]
    #[inline]
    pub fn add_source<E>(mut self, source: E) -> Self
    where
        E: Error + Send + Sync + 'static,
    {
        self.sources
            .get_or_insert_default()
            .push(GErrSource::from_error(source));
        self
    }

    /// Add GErr as error source.
    ///
    /// Any errors implementing `Into<GErrSource>` pass.
    #[inline]
    pub fn add_source_gerr<E>(mut self, gerr: E) -> Self
    where
        E: Into<GErrSource> + Error + Send + Sync + 'static,
    {
        self.sources.get_or_insert_default().push(gerr.into());
        self
    }

    /// Add tag to GErr.
    #[must_use]
    pub fn add_tag<T>(mut self, tag: T) -> Self
    where
        T: Into<Cow<'static, str>>,
    {
        self.tags.get_or_insert_default().push(tag.into());
        self
    }

    /// Add multiple tags at once to GErr.
    #[must_use]
    pub fn add_tags<I, T>(mut self, tags: I) -> Self
    where
        I: IntoIterator<Item = T>,
        T: Into<Cow<'static, str>>,
    {
        let mut tags = tags.into_iter().peekable();
        if tags.peek().is_some() {
            self.tags
                .get_or_insert_default()
                .extend(tags.map(Into::into));
        }
        self
    }

    /// Update error data.
    #[must_use]
    #[inline]
    pub fn set_data(mut self, data: D) -> Self {
        self.data = Some(data);
        self
    }

    /// Update help.
    #[must_use]
    #[inline]
    pub fn set_help<H>(mut self, help: H) -> Self
    where
        H: Into<Cow<'static, str>>,
    {
        self.help = Some(help.into());
        self
    }

    /// Override ID value and type.
    ///
    /// This returns new GErr with different type of ID.
    #[must_use]
    #[inline]
    pub fn with_id<T>(self, id: T) -> GErr<T, P, D> {
        GErr {
            id: Some(id),
            message: self.message,

            prefix: self.prefix,
            sources: self.sources,

            tags: self.tags,

            data: self.data,

            help: self.help,

            location: self.location,

            #[cfg(feature = "backtrace")]
            backtrace: self.backtrace,

            _static_prefix: PhantomData,
        }
    }

    /// Override Prefix(P) value and type.
    ///
    /// This returns new GErr with different type of Prefix.
    #[must_use]
    #[inline]
    pub fn with_prefix<T: Prefix>(self) -> GErr<ID, T, D> {
        GErr {
            id: self.id,
            message: self.message,

            prefix: T::PREFIX.map(Cow::Borrowed),
            sources: self.sources,

            tags: self.tags,

            data: self.data,

            help: self.help,

            location: self.location,

            #[cfg(feature = "backtrace")]
            backtrace: self.backtrace,

            _static_prefix: PhantomData,
        }
    }

    /// Override Data(D) value and type.
    ///
    /// This returns new GErr with different type of Data.
    #[must_use]
    #[inline]
    pub fn with_data<T>(self, data: T) -> GErr<ID, P, T> {
        GErr {
            id: self.id,
            message: self.message,

            prefix: self.prefix,
            sources: self.sources,

            tags: self.tags,

            data: Some(data),

            help: self.help,

            location: self.location,

            #[cfg(feature = "backtrace")]
            backtrace: self.backtrace,

            _static_prefix: PhantomData,
        }
    }

    // --- getter ---

    /// Error id.
    #[inline]
    pub fn id(&self) -> Option<&ID> {
        self.id.as_ref()
    }

    /// Error message.
    #[inline]
    pub fn message(&self) -> &str {
        &self.message
    }

    /// Error prefix.
    #[inline]
    pub fn prefix(&self) -> Option<&str> {
        self.prefix.as_deref().or(P::PREFIX)
    }

    /// Error tags.
    #[inline]
    pub fn tags(&self) -> Option<&[Cow<'static, str>]> {
        self.tags.as_deref()
    }

    /// Iterate over tags.
    #[inline]
    pub fn iter_tags(&self) -> impl Iterator<Item = &str> {
        self.tags.iter().flatten().map(Cow::as_ref)
    }

    /// Error data.
    #[inline]
    pub fn data(&self) -> Option<&D> {
        self.data.as_ref()
    }

    /// Error sources.
    #[inline]
    pub fn sources(&self) -> Option<&[GErrSource]> {
        self.sources.as_deref()
    }

    /// Error location.
    #[inline]
    pub fn location(&self) -> &'static Location<'static> {
        self.location
    }

    /// Error help hint.
    #[inline]
    pub fn help(&self) -> Option<&str> {
        self.help.as_deref()
    }

    /// Error stacktrace, if `backtrace` enabled.
    #[cfg(feature = "backtrace")]
    #[inline]
    pub fn backtrace(&self) -> &std::backtrace::Backtrace {
        &self.backtrace
    }

    /// Returns GErr as `Result<T, GErr<ID, P, D>>`.
    #[inline]
    pub fn result<T>(self) -> Result<T, ID, P, D> {
        Result::Err(self)
    }

    /// Box GErr
    #[inline]
    pub fn boxed(self) -> GErrBox<ID, P, D> {
        Box::new(self)
    }
}

impl<ID, P: Prefix, D> GErr<ID, P, D> {
    /// Update error data's fields provided that the data implement `Default` and [`SetField`].
    ///
    /// [`SetField`] trait implementation is user-defined.
    #[must_use]
    #[inline]
    pub fn set_field<K, V>(mut self, key: K, value: V) -> Self
    where
        D: Default + SetField<K, V>,
    {
        let data = self.data.get_or_insert_with(Default::default);
        data.set_field(key, value);
        self
    }
}

impl<ID, P: Prefix, D> Display for GErr<ID, P, D> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        if let Some(prefix) = self.prefix.as_deref().or(P::PREFIX) {
            write!(f, "{prefix} {}", self.message())
        } else {
            write!(f, "{}", self.message())
        }
    }
}

impl<ID: Debug, P: Prefix, D: Debug> Debug for GErr<ID, P, D> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut debug = f.debug_struct("Err");

        debug
            .field("id", &self.id)
            .field("prefix", &self.prefix.as_deref().or(P::PREFIX))
            .field("message", &self.message)
            .field("source", &self.sources)
            .field("tags", &self.tags)
            .field("data", &self.data)
            .field("help", &self.help())
            .field("location", &self.location);

        #[cfg(feature = "backtrace")]
        debug.field("backtrace", &self.backtrace);

        debug.finish()
    }
}

impl<ID: Debug, P: Prefix, D: Debug> Error for GErr<ID, P, D> {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        if let Some(ref sources) = self.sources
            && !sources.is_empty()
        {
            return sources.first().map(|s| s as &(dyn Error + 'static));
        }
        None
    }
}

#[cfg(not(feature = "serde"))]
impl<ID, P, D> From<GErr<ID, P, D>> for GErrSource
where
    ID: IdSource + 'static,
    D: DataSource + 'static,
{
    fn from(gerr: GErr<ID, P, D>) -> Self {
        GErrSource {
            id: gerr.id.map(|id| Box::new(id) as Box<dyn IdSource>),
            message: gerr.message,
            prefix: gerr.prefix,
            tags: gerr.tags,
            data: gerr.data.map(|d| Box::new(d) as Box<dyn DataSource>),
            help: gerr.help,
            location: Some(gerr.location),
            sources: gerr.sources,
        }
    }
}

#[cfg(not(feature = "serde"))]
impl<ID, P, D> GErr<ID, P, D>
where
    ID: IdSource + 'static,
    D: DataSource + 'static,
{
    /// Converts GErr into [`GErrSource`].
    #[inline]
    pub fn into_gerr_source(self) -> GErrSource {
        self.into()
    }
}

#[cfg(feature = "serde")]
impl<ID, P, D> From<GErr<ID, P, D>> for GErrSource
where
    ID: ::serde::Serialize + IdSource + 'static,
    D: ::serde::Serialize + DataSource + 'static,
{
    fn from(gerr: GErr<ID, P, D>) -> Self {
        GErrSource {
            id_json: gerr
                .id
                .as_ref()
                .map(|v| serde_json::to_value(v).unwrap_or_default()),
            id: gerr.id.map(|id| Box::new(id) as Box<dyn IdSource>),
            message: gerr.message,
            prefix: gerr.prefix,
            tags: gerr.tags,
            data_json: gerr
                .data
                .as_ref()
                .map(|d| serde_json::to_value(d).unwrap_or_default()),
            data: gerr.data.map(|d| Box::new(d) as Box<dyn DataSource>),
            help: gerr.help,
            location: Some(gerr.location),
            sources: gerr.sources,
        }
    }
}

#[cfg(feature = "serde")]
impl<ID, P, D> GErr<ID, P, D>
where
    ID: ::serde::Serialize + IdSource + 'static,
    D: ::serde::Serialize + DataSource + 'static,
{
    /// Converts GErr into [`GErrSource`].
    #[inline]
    pub fn into_gerr_source(self) -> GErrSource {
        self.into()
    }
}
